import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import { NavbarWrapper } from "@/components/navbar/navbar-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
    <ClerkProvider>
      <html>
        <body className="bg-slate-600 text-white">
          <NavbarWrapper />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
