import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import { NavbarWrapper } from "@/components/navbar/navbar-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


 return (
    <ClerkProvider>
      <NavbarWrapper />
      <html>
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
